<div class="col-md-12">
    <h3>Novo Perfil do Usuário</h3>
    <?php
        echo $this->form()->openTag($form);
            echo $this->formHidden($form->get('seqUsuarioPerfil'));
            echo $this->elementToRow($form->get('seqUsuario'));
            echo $this->elementToRow($form->get('seqPerfil'));
            echo $this->formSubmit($form->get('submit'));
        echo $this->form()->closeTag();
    ?>
</div>