<?php
    if (sizeof($this->menuButtons))
        $this->menuBar($this->menuButtons);
?>
<div class="row">
    <div class="col-md-12">
        <table class="table table-bordered table-hover table-condensed">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Perfil</th>
                    <th>Usuário</th>
                    <th style="width:27px;"></th>
                    <th style="width:27px;"></th>
                </tr>
            </thead>
            <tbody>
                <?php

                    foreach ($this->usuarioPerfil as $key => $value) {
                        echo "<tr>";
                        echo    "<td>".$value->seq_usuario_perfil."</td>";
                        echo    "<td>".$value->des_perfil."</td>";
                        echo    "<td>".$value->nom_usuario."</td>";
                        echo    "<td>
                                    <a class='btn btn-mini btn-warning' href='/admin/perfis-usuarios/update/".$value->seq_usuario_perfil."' data-id='".$value->seq_usuario_perfil."'>
                                        <i class='fa fa-pencil'></i>
                                    </a>
                                </td>";
                            echo    "<td>
                                        <a class='btn btn-mini btn-danger btn-window-confirm' href='#' data-id='".$value->seq_usuario_perfil."'>
                                            <i class='fa fa-trash-o'></i>
                                        </a>
                                    </td>";
                        echo "</tr>";

                    }
                ?>
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript">

    $(".btn-window-confirm").click(function(e){

        var itemSelecionado = $(e.currentTarget).data('id');
        bootbox.confirm("Você tem certeza que deseja excluir o perfil do usuário?", function(result) {
            if (result)
            {
                window.location.href = '/admin/perfis-usuarios/delete/' + itemSelecionado;
            }
        });
    });

</script>