<?php echo $this->doctype(); ?>

<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Webbsb ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('css/bootstrap/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('css/libs/font-awesome.css'))
        ->prependStylesheet($this->basePath('css/libs/nanoscroller.css'))
        ->prependStylesheet($this->basePath('css/compiled/theme_styles.css'))
        ->prependStylesheet($this->basePath('css/libs/daterangepicker.css'))
        ->prependStylesheet($this->basePath('css/libs/jquery-jvectormap-1.2.2.css'))
        ->prependStylesheet($this->basePath('css/libs/weather-icons.css'))
        ->prependStylesheet($this->basePath('css/libs/morris.css'))
    ?>

    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,600,700,300' rel='stylesheet' type='text/css'>
    <!--[if lt IE 9]>
    <script src="<?php echo $this->basePath() . '/js/html5shiv.js' ?>"></script>
    <script src="<?php echo $this->basePath() . '/js/respond.min.js' ?>"></script>
    <![endif]-->

    <script src="<?php echo $this->basePath() . '/js/demo-rtl.js' ?>"></script>
    <script src="<?php echo $this->basePath() . '/js/jquery.js' ?>"></script>
    <script src="<?php echo $this->basePath() . '/js/bootstrap.js' ?>"></script>

</head>
<body>
<div id="theme-wrapper">
    <?php
    $user = $this->session()->offsetGet('zf2base_loggeduser');
    if ($user):
    ?>
    <?php echo $this->render('layout-menu-top.phtml'); ?>


    <div id="page-wrapper" class="container">
        <div class="row">
            <?php echo $this->render('layout-siderbar.phtml'); ?>

            <div id="content-wrapper">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="row">
                            <div class="col-lg-12">
                                <div id="content-header" class="clearfix">
                                    <div class="pull-left">
                                        <ol class="breadcrumb">
                                            <li><a href="#">Home</a></li>
                                            <li class="active"><span>Dashboard</span></li>
                                        </ol>
                                        <h1>Dashboard - WEBBSB</h1>
                                    </div>
                                    <div class="pull-right hidden-xs">
                                        <div class="xs-graph pull-left">
                                            <div class="graph-label">
                                                <b><i class="fa fa-shopping-cart"></i> 838</b> Orders
                                            </div>
                                            <div class="graph-content spark-orders"></div>
                                        </div>
                                        <div class="xs-graph pull-left mrg-l-lg mrg-r-sm">
                                            <div class="graph-label">
                                                <b>&dollar;12.338</b> Revenues
                                            </div>
                                            <div class="graph-content spark-revenues"></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <?php echo $this->content; ?>
                    </div>
                </div>
                <footer id="footer-bar" class="row">
                    <p id="footer-copyright" class="col-xs-12">
                        Powered by WebBSB.
                    </p>
                </footer>
            </div>
        </div>
    </div>
</div>

<?php echo $this->render('layout-config-tool.phtml'); ?>

<?php
else:
    echo $this->render('layout-login.phtml');
endif;
?>

<?php echo $this->inlineScript() ?>

<script src="<?php echo $this->basePath() . '/js/demo-skin-changer.js' ?>"></script>
<script src="<?php echo $this->basePath() . '/js/jquery.nanoscroller.min.js' ?>"></script>
<script src="<?php echo $this->basePath() . '/js/demo.js' ?>"></script>
<script src="<?php echo $this->basePath() . '/js/jquery.scrollTo.min.js' ?>"></script>
<script src="<?php echo $this->basePath() . '/js/jquery.slimscroll.min.js' ?>"></script>
<script src="<?php echo $this->basePath() . '/js/jquery-jvectormap-1.2.2.min.js' ?>"></script>
<script src="<?php echo $this->basePath() . '/js/jquery-jvectormap-world-merc-en.js' ?>"></script>
<script src="<?php echo $this->basePath() . '/js/gdp-data.js' ?>"></script>
<script src="<?php echo $this->basePath() . '/js/flot/jquery.flot.min.js' ?>"></script>
<script src="<?php echo $this->basePath() . '/js/flot/jquery.flot.resize.min.js' ?>"></script>
<script src="<?php echo $this->basePath() . '/js/flot/jquery.flot.time.min.js' ?>"></script>
<script src="<?php echo $this->basePath() . '/js/flot/jquery.flot.threshold.js' ?>"></script>
<script src="<?php echo $this->basePath() . '/js/flot/jquery.flot.axislabels.js' ?>"></script>
<script src="<?php echo $this->basePath() . '/js/jquery.sparkline.min.js' ?>"></script>
<script src="<?php echo $this->basePath() . '/js/skycons.js' ?>"></script>
<script src="<?php echo $this->basePath() . '/js/raphael-min.js' ?>"></script>
<script src="<?php echo $this->basePath() . '/js/morris.js' ?>"></script>
<script src="<?php echo $this->basePath() . '/js/scripts.js' ?>"></script>
<script src="<?php echo $this->basePath() . '/js/pace.min.js' ?>"></script>
<script src="<?php echo $this->basePath() . '/js/personalizado.js' ?>"></script>
<script src="<?php echo $this->basePath() . '/js/bootbox.min.js' ?>"></script>


</body>
</html>
