<?php echo $this->doctype(); ?>

<html lang="pt_br">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Base de Sistema ')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/btn-app.min.css')
                        ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css');
        
        echo $this->headScript()->prependFile($this->basePath() . '/js/jquery-1.11.min.js');

        ?>
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <div class="navbar navbar-default navbar-static-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Barra de navegação</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Base de Sistema</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <?php
                            $user = $this->session()->offsetGet('zf2base_loggeduser');
                            if ($user):
                        ?>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <span id="user_info">
                                        <small>Bem Vindo(a),</small> <?php echo $user->getNomUsuario(); ?>
                                    </span>
                                    <b class="caret"></b>
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a href="#"><i class="fa fa-cog"></i> Configuração</a></li>
                                    <li><a href="#"><i class="fa fa-user"></i> Editar Perfil</a></li>
                                    <li><a href="/application/auth/logout"><i class="icon-off"></i> Sair</a></li>
                                </ul>
                            </li>
                    <?php endif;?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </div>

        <div class="container">

            <?php
                echo $this->navigation('navigation')->breadcrumbs()->setMinDepth(0)->setSeparator('/')->setPartial(array('application/partials/breadcrumbs', 'Admin'));
            ?>

            <div class="row">
                <div class="col-md-3 sidebar">
                    <ul class="nav nav-sidebar">
                        <li class="active">
                          <a href="/admin/index">
                            <i class="fa fa-cog"></i>
                            <span>Página principal</span>
                          </a>
                        </li>
                        <li>
                          <a href="/admin/usuarios">
                            <i class="fa fa-user"></i>
                            <span>Usuários</span>
                          </a>
                        </li>
                        <li>
                          <a href="/admin/perfis">
                            <i class="fa fa-check"></i>
                            <span>Perfis</span>
                          </a>
                        </li>
                        <li>
                            <a href="/admin/perfis-usuarios">
                                <i class="fa fa-check"></i>
                                <span>Perfil Usuário</span>
                            </a>
                        </li>
                    </ul>
                </div>

                <div class="col-md-9">
                    
                    <?php
                        $message = $this->flashMessage();
                        echo strlen($message) > 0 ? $message : '';
                    ?>

                    <?php echo $this->content; ?>
                </div>
            </div>
        </div>
<!-- Scripts -->
        <?php 
            echo $this->headScript()->prependFile($this->basePath() . '/js/bootbox.min.js')
                                    ->prependFile($this->basePath() . '/js/bootstrap.min.js');
            
            echo $this->inlineScript();
        ?>
    </body>
</html>
