<div class="col-md-12">
    <h3>Atualizar Usuário</h3>
    <?php
        echo $this->form()->openTag($form);
            echo $this->formHidden($form->get('seqUsuario'));
//            $usuarioCadastrou = $form->getElements();
//            $usuarioCadastrou['seqUsuarioCadastrou']->setValue($form->get('seqUsuarioCadastrou')->getValue()->getSeqUsuario());
//            echo $this->formHidden($usuarioCadastrou['seqUsuarioCadastrou']->setValue($form->get('seqUsuarioCadastrou')->getValue()));
            echo $this->formHidden($form->get('seqUsuarioCadastrou'));
            echo $this->elementToRow($form->get('nomUsuario'));
            echo $this->elementToRow($form->get('desEmail'));
            echo $this->elementToRow($form->get('desSenha'));
            echo $this->formSubmit($form->get('submit'));
        echo $this->form()->closeTag();
    ?>
</div>