<?php

$urlPattern = $_SERVER['REQUEST_URI'];

$formatUrl = function ($page) use ($urlPattern) {

    if (!preg_match('/page/', $urlPattern))
        return $urlPattern . '/page/' . (int)$page;
    else
        return preg_replace('@/page/\d@', '/page/' . (int)$page, $urlPattern);
};

?>

<center>
    <?php if ($this->pageCount): ?>
        <div class="">
            <span class="badge bg-green"><?php echo $this->firstItemNumber; ?></span> -
            <span class="badge bg-green"><?php echo $this->lastItemNumber; ?></span> de
            <span class="badge bg-yellow"><?php echo $this->totalItemCount; ?> registros</span>
            <br/>
            <br/>

            <ul class="pagination pagination-sm no-margin">
                <!-- First page link -->
                <?php if (isset($this->previous)): ?>
                    <li>
                        <a href="<?php echo $formatUrl($this->previous) ?>"> Primeira </a>
                    </li>
                <?php else: ?>
                    <li class="disabled"><a>Primeira</a></li>
                <?php endif; ?>


                <!-- Previous page link -->
                <?php if (isset($this->previous)): ?>
                    <li>
                        <a href="<?php echo $formatUrl($this->previous) ?>"> < Anterior</a>
                    </li>
                <?php else: ?>
                    <li class="disabled"><a>< Anterior</a></li>
                <?php endif; ?>


                <!-- Next page link -->
                <?php if (isset($this->next)): ?>
                    <li>
                        <a href="<?php echo $formatUrl($this->next); ?>"> Próximo > </a>
                    </li>
                <?php else: ?>
                    <li class="disabled"><a>Próximo ></a></li>
                <?php endif; ?>


                <!-- Last page link -->
                <?php if (isset($this->last)): ?>
                    <li>
                        <a href="<?php echo $formatUrl($this->last); ?>"> Último </a>
                    </li>
                <?php else: ?>
                    <li class="disabled"><a>Último</a></li>
                <?php endif; ?>
            </ul>
        </div>

    <?php endif; ?>
</center>
