<?php

if (sizeof($this->menuButtons))
    $this->menuBar($this->menuButtons);
?>
<div class="row">

    <div class="col-md-12">

        <div class="col-md-12">
            <form action="/admin/perfis" method="post" name="novoPerfil" class="form-horizontal" id="novoPerfil">
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="nomPerfil">Nome do perfil</label>

                    <div class="col-sm-4">
                        <input type="text" name="nomPerfil" id="nomPerfil" placeholder="Nome do perfil"
                               class="form-control" value="">
                    </div>

                    <label class="col-sm-2 control-label" for="sitPerfil">Situação</label>

                    <div class="col-sm-4">
                        <select class="select2-choice" name="sitPerfil" id="sitPerfil">Situação
                            <option value="">selecione uma opção</option>
                            <option value="A">Ativo</option>
                            <option value="I">Inativo</option>
                        </select>
                    </div>
                </div>
                <div class="button">
                    <input type="submit" name="submit" class="btn btn-info" value="Pesquisar">
                </div>
            </form>
        </div>


        <table class="table table-bordered table-hover table-condensed">
            <thead>
            <tr>
                <th>#</th>
                <th>Perfil</th>
                <th>Descrição</th>
                <th style="width:40px;">Situação</th>
                <th style="width:27px;"></th>
                <th style="width:27px;"></th>
            </tr>
            </thead>
            <tbody>
            <?php

            foreach ($this->perfis as $key => $value) {
                $situacao = $value->getSitPerfil() == 'A' ? 'Ativo' : 'Inativo';
                echo "<tr>";
                echo "<td>" . $value->getSeqPerfil() . "</td>";
                echo "<td>" . $value->getNomPerfil() . "</td>";
                echo "<td>" . $value->getDesPerfil() . "</td>";
                echo "<td>" . $situacao . "</td>";
                echo "<td>
                                    <a class='btn btn-mini btn-warning' href='/admin/perfis/update/" . $value->getSeqPerfil() . "' data-id='" . $value->getSeqPerfil() . "'>
                                        <i class='fa fa-pencil'></i>
                                    </a>
                                </td>";
                if ($value->getSitPerfil() == 'A') :
                    echo "<td>
                                        <a class='btn btn-mini btn-danger btn-window-confirm' href='#' data-id='" . $value->getSeqPerfil() . "'>
                                            <i class='fa fa-trash-o'></i>
                                        </a>
                                    </td>";
                endif;
                echo "</tr>";

            }
            ?>
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript">

    $(".btn-window-confirm").click(function (e) {

        var itemSelecionado = $(e.currentTarget).data('id');
        bootbox.confirm("Você tem certeza que deseja excluir esse perfil?", function (result) {
            if (result) {
                window.location.href = '/admin/perfis/inactive/' + itemSelecionado;
            }
        });
    });

</script>